server:
    port: 28082
    tomcat:
        uri-encoding: UTF-8

spring:
    profiles:
        active: 

mybatis:
    mapper-locations: classpath*:sqlmapper/*.xml
    type-aliases-package: com.sbsft.wslapi.domain
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 20
        default-statement-timeout: 30











