spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/wslt?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=Asia/Seoul
        driver-class-name: org.mariadb.jdbc.Driver
        username: shrturlsrv
        password: 8Yj(TSK<7Q~qE,?T













